server:
  port: 8080

spring:
  application:
    name: anonymous-vote-backend

  datasource:
    url: jdbc:mysql://localhost:3306/anonymous_vote_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: anonymous_vote
    password: 'anonymous_vote@123'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
